export interface LabTest {
  key: string;
  name: string;
  aliases?: string[];
  category: string;
  unit: string;
  whatItIs: string;
  whyItMatters: string;
  ranges: { label: string; range: string; severity: "good" | "watch" | "warn" }[];
  tips: string[];
}

export const LAB_LIBRARY: LabTest[] = [
  {
    key: "fastingGlucose",
    name: "Fasting Glucose",
    aliases: ["FBS", "Fasting Blood Sugar"],
    category: "Blood Sugar",
    unit: "mg/dL",
    whatItIs: "Sugar level in your blood after at least 8 hours without food.",
    whyItMatters: "Helps screen for prediabetes and diabetes. Persistent high readings damage blood vessels and nerves.",
    ranges: [
      { label: "Normal", range: "70 – 99", severity: "good" },
      { label: "Prediabetes", range: "100 – 125", severity: "watch" },
      { label: "Diabetes range", range: "≥ 126", severity: "warn" },
    ],
    tips: ["Reduce refined sugar and white carbs", "Walk 10–15 min after meals", "Aim for 7+ hrs of sleep"],
  },
  {
    key: "hba1c",
    name: "HbA1c",
    aliases: ["Glycated Hemoglobin", "A1C"],
    category: "Blood Sugar",
    unit: "%",
    whatItIs: "Average blood sugar over the past ~3 months.",
    whyItMatters: "The single best long-term marker of glucose control.",
    ranges: [
      { label: "Normal", range: "< 5.7", severity: "good" },
      { label: "Prediabetes", range: "5.7 – 6.4", severity: "watch" },
      { label: "Diabetes", range: "≥ 6.5", severity: "warn" },
    ],
    tips: ["Cut sugary drinks", "Add fiber: oats, beans, vegetables", "Strength train 2x/week"],
  },
  {
    key: "ldl",
    name: "LDL Cholesterol",
    aliases: ["Bad Cholesterol"],
    category: "Lipids",
    unit: "mg/dL",
    whatItIs: "The 'sticky' cholesterol that can build up in artery walls.",
    whyItMatters: "Higher LDL raises your risk of heart attack and stroke.",
    ranges: [
      { label: "Optimal", range: "< 100", severity: "good" },
      { label: "Borderline", range: "100 – 159", severity: "watch" },
      { label: "High", range: "≥ 160", severity: "warn" },
    ],
    tips: ["Replace butter with olive oil", "Eat oats, nuts, fatty fish", "150 min/week of cardio"],
  },
  {
    key: "hdl",
    name: "HDL Cholesterol",
    aliases: ["Good Cholesterol"],
    category: "Lipids",
    unit: "mg/dL",
    whatItIs: "The 'cleanup' cholesterol that removes LDL from your bloodstream.",
    whyItMatters: "Higher HDL is protective against heart disease.",
    ranges: [
      { label: "Low (risk)", range: "< 40 (M) / < 50 (F)", severity: "warn" },
      { label: "Better", range: "40 – 60", severity: "watch" },
      { label: "Protective", range: "> 60", severity: "good" },
    ],
    tips: ["Regular exercise raises HDL", "Quit smoking", "Use healthy fats: avocado, nuts, olive oil"],
  },
  {
    key: "triglycerides",
    name: "Triglycerides",
    category: "Lipids",
    unit: "mg/dL",
    whatItIs: "A type of fat in your blood, mostly from excess calories.",
    whyItMatters: "High levels worsen heart risk and may signal metabolic issues.",
    ranges: [
      { label: "Normal", range: "< 150", severity: "good" },
      { label: "Borderline", range: "150 – 199", severity: "watch" },
      { label: "High", range: "≥ 200", severity: "warn" },
    ],
    tips: ["Cut sugary drinks and alcohol", "Reduce refined carbs", "Add omega-3 (fish, walnuts, flax)"],
  },
  {
    key: "tsh",
    name: "TSH",
    aliases: ["Thyroid Stimulating Hormone"],
    category: "Thyroid",
    unit: "mIU/L",
    whatItIs: "Hormone from the pituitary that tells the thyroid how hard to work.",
    whyItMatters: "High TSH suggests an underactive thyroid; low TSH suggests overactive.",
    ranges: [
      { label: "Normal", range: "0.4 – 4.0", severity: "good" },
      { label: "High (hypothyroid)", range: "> 4.0", severity: "warn" },
      { label: "Low (hyperthyroid)", range: "< 0.4", severity: "warn" },
    ],
    tips: ["Eat enough iodine (iodized salt, dairy, fish)", "Manage stress", "Don't self-medicate; see an endocrinologist"],
  },
  {
    key: "alt",
    name: "ALT (SGPT)",
    aliases: ["SGPT"],
    category: "Liver",
    unit: "U/L",
    whatItIs: "An enzyme released when liver cells are damaged.",
    whyItMatters: "Elevated ALT is a sensitive sign of liver stress (alcohol, fatty liver, medications).",
    ranges: [
      { label: "Normal", range: "7 – 56", severity: "good" },
      { label: "Mildly elevated", range: "57 – 100", severity: "watch" },
      { label: "Significantly high", range: "> 100", severity: "warn" },
    ],
    tips: ["Cut alcohol", "Lose excess weight slowly", "Avoid unnecessary supplements/painkillers"],
  },
  {
    key: "ast",
    name: "AST (SGOT)",
    aliases: ["SGOT"],
    category: "Liver",
    unit: "U/L",
    whatItIs: "An enzyme found in the liver, heart, and muscles. Released when these tissues are stressed.",
    whyItMatters: "Together with ALT, helps assess liver injury.",
    ranges: [
      { label: "Normal", range: "10 – 40", severity: "good" },
      { label: "Elevated", range: "> 40", severity: "warn" },
    ],
    tips: ["Limit alcohol", "Stay hydrated", "Discuss medication side-effects with your doctor"],
  },
  {
    key: "creatinine",
    name: "Creatinine",
    category: "Kidney",
    unit: "mg/dL",
    whatItIs: "Waste from muscle activity. Cleared by the kidneys.",
    whyItMatters: "Higher creatinine suggests kidneys may not be filtering well.",
    ranges: [
      { label: "Normal", range: "0.6 – 1.2", severity: "good" },
      { label: "Elevated", range: "> 1.2", severity: "warn" },
    ],
    tips: ["Stay hydrated", "Limit excess protein supplements", "Control blood pressure and sugar"],
  },
  {
    key: "urea",
    name: "Urea (BUN)",
    aliases: ["BUN"],
    category: "Kidney",
    unit: "mg/dL",
    whatItIs: "Waste from protein breakdown filtered by the kidneys.",
    whyItMatters: "Both kidney function and hydration affect this number.",
    ranges: [
      { label: "Normal", range: "10 – 50", severity: "good" },
      { label: "High", range: "> 50", severity: "warn" },
    ],
    tips: ["Drink enough water through the day", "Moderate protein intake", "Treat any UTI promptly"],
  },
  {
    key: "uricAcid",
    name: "Uric Acid",
    category: "Kidney",
    unit: "mg/dL",
    whatItIs: "Waste from breaking down purines (found in meat, seafood, alcohol).",
    whyItMatters: "High levels cause gout and increase kidney stone risk.",
    ranges: [
      { label: "Normal", range: "3.5 – 7.0", severity: "good" },
      { label: "High", range: "> 7.0", severity: "warn" },
    ],
    tips: ["Limit red meat, organ meat, beer", "Drink more water", "Eat cherries and low-fat dairy"],
  },
  {
    key: "hemoglobin",
    name: "Hemoglobin",
    aliases: ["Hb"],
    category: "CBC",
    unit: "g/dL",
    whatItIs: "Protein in red cells that carries oxygen around your body.",
    whyItMatters: "Low hemoglobin (anemia) causes fatigue, breathlessness, pale skin.",
    ranges: [
      { label: "Normal (M)", range: "13.5 – 17.5", severity: "good" },
      { label: "Normal (F)", range: "12.0 – 15.5", severity: "good" },
      { label: "Anemia", range: "Below normal", severity: "warn" },
    ],
    tips: ["Eat iron-rich foods (spinach, lentils, red meat)", "Pair with vitamin C", "Get checked for cause if low"],
  },
  {
    key: "vitaminD",
    name: "Vitamin D (25-OH)",
    category: "Vitamins",
    unit: "ng/mL",
    whatItIs: "Hormone-like vitamin made in skin from sunlight, also from fish and supplements.",
    whyItMatters: "Critical for bones, immunity, mood, and muscle strength.",
    ranges: [
      { label: "Deficient", range: "< 20", severity: "warn" },
      { label: "Insufficient", range: "20 – 29", severity: "watch" },
      { label: "Sufficient", range: "30 – 60", severity: "good" },
    ],
    tips: ["15–20 min midday sun on arms/legs", "Fatty fish, egg yolks, fortified milk", "Supplement under medical advice"],
  },
  {
    key: "vitaminB12",
    name: "Vitamin B12",
    category: "Vitamins",
    unit: "pg/mL",
    whatItIs: "Vitamin needed for nerves and red blood cells. Found in animal foods.",
    whyItMatters: "Deficiency causes fatigue, tingling, memory issues — common in vegetarians and older adults.",
    ranges: [
      { label: "Low", range: "< 200", severity: "warn" },
      { label: "Borderline", range: "200 – 300", severity: "watch" },
      { label: "Normal", range: "> 300", severity: "good" },
    ],
    tips: ["Eat eggs, dairy, fish, meat", "Vegetarians: fortified cereals or supplement", "Sublingual B12 absorbs well"],
  },
  {
    key: "ferritin",
    name: "Ferritin",
    category: "Vitamins",
    unit: "ng/mL",
    whatItIs: "Stored form of iron in the body.",
    whyItMatters: "Low ferritin signals depleted iron stores even before anemia shows up.",
    ranges: [
      { label: "Low (M)", range: "< 30", severity: "warn" },
      { label: "Low (F)", range: "< 15", severity: "warn" },
      { label: "Normal", range: "30 – 300", severity: "good" },
    ],
    tips: ["Iron-rich foods + vitamin C", "Avoid tea/coffee with meals", "Cook in iron utensils"],
  },
  {
    key: "crp",
    name: "CRP",
    aliases: ["C-reactive Protein"],
    category: "Inflammation",
    unit: "mg/L",
    whatItIs: "A protein your liver releases when there's inflammation.",
    whyItMatters: "Elevated CRP signals infection, injury, or chronic inflammation.",
    ranges: [
      { label: "Low", range: "< 1", severity: "good" },
      { label: "Average", range: "1 – 3", severity: "watch" },
      { label: "High", range: "> 3", severity: "warn" },
    ],
    tips: ["Anti-inflammatory diet (fish, olive oil, vegetables)", "Sleep well", "Manage chronic conditions"],
  },
  {
    key: "sodium",
    name: "Sodium",
    category: "Electrolytes",
    unit: "mEq/L",
    whatItIs: "Key electrolyte that controls fluid balance.",
    whyItMatters: "Imbalance causes confusion, weakness, and serious heart issues.",
    ranges: [
      { label: "Normal", range: "135 – 145", severity: "good" },
      { label: "Low (hyponatremia)", range: "< 135", severity: "warn" },
      { label: "High (hypernatremia)", range: "> 145", severity: "warn" },
    ],
    tips: ["Don't over-drink water during exercise", "Don't restrict salt without doctor's advice", "Stay hydrated normally"],
  },
  {
    key: "potassium",
    name: "Potassium",
    category: "Electrolytes",
    unit: "mEq/L",
    whatItIs: "Electrolyte essential for heart rhythm and muscle function.",
    whyItMatters: "Both low and high levels can be dangerous for the heart.",
    ranges: [
      { label: "Normal", range: "3.5 – 5.0", severity: "good" },
      { label: "Low", range: "< 3.5", severity: "warn" },
      { label: "High", range: "> 5.0", severity: "warn" },
    ],
    tips: ["Bananas, potatoes, oranges for low potassium", "If high: avoid salt substitutes (KCl)", "Discuss any heart medications"],
  },
];
