import { Button } from "@/components/ui/button";
import { CalendarPlus } from "lucide-react";
import { AnalysisResult } from "@/lib/types";
import { buildReminderICS, downloadICS, ReminderEvent } from "@/lib/calendar";
import { useToast } from "@/hooks/use-toast";

export function RemindersButton({ report }: { report: AnalysisResult }) {
  const { toast } = useToast();

  const handleDownload = () => {
    const events: ReminderEvent[] = [];
    const seen = new Set<string>();

    report.followUp?.forEach(f => {
      const key = f.test;
      if (seen.has(key)) return;
      seen.add(key);
      const weeks = parseTimeframe(f.when);
      events.push({
        title: `Re-check: ${f.test}`,
        description: `${f.why}\n\nGenerated by HealthAdvisor.`,
        weeksFromNow: weeks,
      });
    });

    if (events.length === 0) {
      events.push({
        title: "Annual health check-up",
        description: "Yearly preventive lab work.",
        weeksFromNow: 52,
      });
    }

    const ics = buildReminderICS(events);
    downloadICS(`health-reminders-${new Date().toISOString().slice(0, 10)}.ics`, ics);
    toast({ title: "Reminders downloaded", description: "Open the file to add to your calendar." });
  };

  return (
    <Button variant="outline" onClick={handleDownload} className="gap-2">
      <CalendarPlus className="h-4 w-4" />
      Add Reminders
    </Button>
  );
}

function parseTimeframe(tf: string): number {
  const lower = tf.toLowerCase();
  const num = parseInt(lower.match(/\d+/)?.[0] ?? "8", 10);
  if (lower.includes("week")) return num;
  if (lower.includes("month")) return num * 4;
  if (lower.includes("year")) return num * 52;
  if (lower.includes("day")) return Math.max(1, Math.round(num / 7));
  return 8;
}
